### ISSUE TITLE
apt(-get) install and apt upgrade calls are not using "-y"

### ISSUE THREAD

**Issue by epneo-sebastianbaier** [zephyrproject-rtos/action-zephyr-setup#11]
Hi,
I tested you 'action-zephyr-setup ' with nektos/act locally and it did proceed after your calls of 'apt-get install' and 'apt update', as they don't use the '-y' parameter. 

Modifing your actions.yml fixed it. 

Greetings
Sebastian

**Comment by fabiobaltieri** [comment]
@epneo-sebastianbaier thanks for troubleshooting this, could you open a pull request with the change?

**Comment by fabiobaltieri** [comment]
> This means, your actions run perfectly fine in GitHub, but not if tested locally with nektos/act. Should I still create a PR?

Yeah I don't see any drawback in specifying that flag all the time, I would have expected apt-get to detect that the output is not a tty and skip it automatically but I see other workflows in the main repo with the flag as well so I guess it makes sense.

**Comment by epneo-sebastianbaier** [comment]
@fabiobaltieri here is the PR:

https://github.com/zephyrproject-rtos/action-zephyr-setup/pull/12

**Comment by henrikbrixandersen** [comment]
This is not completed until the PR is merged.

**Comment by epneo-sebastianbaier** [comment]
Ok, I thought, that there is no further discussion needed and the rest can be handled in the PR. That's why i closed it.
